# Información básica del libro
title: Fundamentos de Física de Semiconductores
author: Rubén Velázquez Hernández
logo: recursos/imagenes/Logo_uteq.png
copyright: "2025"
html:
  use_repository_button: true
  extra_footer: |
    <div>
      <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
        <img src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" alt="Creative Commons License" />
      </a>
      <br />Este trabajo está bajo una 
      <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
        Licencia Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
      </a>.
    </div>
only_build_toc_files: true

# Configuración de Jupyter Book
repository:
  url: https://github.com/Neburok/Fundamentos_Fisica_Semiconductores
  branch: main

# Configuración de ejecución
execute:
  execute_notebooks: force  # Opciones: auto, force, cache, off
  timeout: 100              # Límite de tiempo para ejecutar celdas (segundos)

# Configuración HTML
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections: true
  home_page_in_navbar: true
  baseurl: https://Neburok.github.io/Fundamentos_Fisica_Semiconductores

# Configuraciones adicionales para widgets interactivos
sphinx:
  extra_extensions:
    - 'IPython.sphinxext.ipython_console_highlighting'
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js


